name: Publish to PyPI

on:
  push:
    tags:
      - "v*"  # Runs when you push a tag like v1.0.0
  workflow_dispatch:  # Allows manual execution

permissions:
  id-token: write  # Required for OIDC authentication

jobs:
  build-and-publish:
    name: Build and Publish Package
    runs-on: ubuntu-latest
    environment: release

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.8"

      - name: Install dependencies
        run: pip3 install -r requirements.txt

      - name: Build package
        run: python3 setup.py sdist bdist_wheel

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1  # Uses OIDC authentication
      
      - name: Upload built package as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: built-package
          path: dist/
          retention-days: 7