name: Publish to PyPI

on:
  push:
    tags:
      - "v*"  # Runs when you push a tag like v1.0.0
  workflow_dispatch:  # Allows manual execution

permissions:
  id-token: write  # Required for OIDC authentication

jobs:
  build-and-publish:
    name: Build and Publish Package
    runs-on: ubuntu-latest
    environment: release

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.8"

      - name: Extract version from setup.py
        id: get_version
        run: |
          VERSION=$(python setup.py --version)
          echo "Extracted version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_ENV

      - name: Compare Tag with Version
        run: |
          TAG_VERSION=${{ github.ref_name }}
          TAG_VERSION=${TAG_VERSION#v}  # Remove 'v' prefix from tag
          
          if [ "$TAG_VERSION" != "$version" ]; then
            echo "ERROR: Tag version ($TAG_VERSION) does not match setup.py version ($version)"
            exit 1
          fi
        shell: bash

      - name: Install dependencies
        run: pip3 install -r requirements.txt

      - name: Build package
        run: python3 setup.py sdist bdist_wheel

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1  # Uses OIDC authentication
      
      - name: Upload built package as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: built-package
          path: dist/
          retention-days: 7
